export default {
  axeSharpness: {
    id: 'axeSharpness',
    text: {
      beforeLink: "With",
      link: "sharper axes, ",
      afterLink: "we could chop faster."
    },
    name: "Axe Sharpness",
    baseCost: 15,
    multiplier: 1.15,
    costs: "energy",
    incomeRate: 0.1,
    industry: "lumber",
  },
  sawTeam: {
    id: 'sawTeam',
    text: {
      beforeLink: "But we should be investing in the newer technologies, like these saws!  The",
      link: "two person teams ",
      afterLink: "we can form will perform as efficiently as five persons did before!",
    },
    name: "Saw Team",
    peopleCost: 2,
    baseCost: 100,
    multiplier: 1.15,
    costs: "energy",
    incomeRate: 0.5,
    industry: "lumber",
  },
  sawMill: {
    id: 'sawMill',
    text: {
      beforeLink: "Unfortunately, the bigger our operation, the harder it is to haul wood to be cut to size.  We should",
      link: "construct buildings",
      afterLink: "near the forest, and cut the wood there.",
    },
    name: "Saw Mill",
    peopleCost: 16,
    baseCost: 500,
    multiplier: 1.15,
    costs: "energy",
    incomeRate: 4,
    industry: "lumber",
  },
  bellPit: {
    id: 'bellPit',
    text: {
      beforeLink: "",
      link: "Dig straight down",
      afterLink: "there's coal down there.  We'll lower someone down to mine it.",
    },
    name: "Bell Pit",
    baseCost: 3000,
    multiplier: 1.15,
    costs: "energy",
    incomeRate: 10,
    industry: "coal",
  },
  driftMine: {
    id: 'driftMine',
    text: {
      beforeLink: "",
      link: "",
      afterLink: ""
    },
    name: "Drift Mine",
    baseCost: 10000,
    multiplier: 1.15,
    costs: "energy",
    incomeRate: 40,
    industry: "coal",
  },
  oilWell: {
    id: 'oilWell',
    name: "Oil Well",
    baseCost: 40000,
    multiplier: 1.15,
    costs: "energy",
    incomeRate: 100,
    industry: "oil",
  },
  oilField: {
    id: 'oilField',
    name: "Oil Field",
    baseCost: 200000,
    multiplier: 1.15,
    costs: "energy",
    incomeRate: 400,
    industry: "oil",
  },
  tidalGenerator: {
    id: 'tidalGenerator',
    name: "Tidal Generator",
    baseCost: 1666666,
    multiplier: 1.15,
    costs: "energy",
    incomeRate: 6666,
    industry: "renewable",
  },
  nuclearReactor: {
    id: 'nuclearReactor',
    name: "Nuclear Reactor",
    baseCost: 123456789,
    multiplier: 1.15,
    costs: "energy",
    incomeRate: 98765,
    industry: "nuclear",
  },
  nuclearPlant: {
    id: 'nuclearPlant',
    name: "Nuclear Plant",
    baseCost: 3999999999,
    multiplier: 1.15,
    costs: "energy",
    incomeRate: 999999,
    industry: "nuclear",
  },
  coldFusion: {
    id: 'coldFusion',
    name: "Cold Fusion",
    baseCost: 75000000000,
    multiplier: 1.15,
    costs: "energy",
    incomeRate: 10000000,
    industry: "nuclear",
  }
}
